version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT} 
      - NATS_SERVERS=nats://nats-server:4222
    image: client-gateway

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    image: products-ms

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args: # Pass build-time variables
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DB_URL}
    image: orders-ms

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    image: payments-ms

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    image: auth-ms